version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: glpi_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    volumes:
      - db_data:/var/lib/mysql

  glpi:
    build: .
    container_name: glpi
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - /home/ilak/projects/glpi/:/var/www/html
    environment:
      GLPI_DB_HOST: db
      GLPI_DB_NAME: glpi
      GLPI_DB_USER: glpi
      GLPI_DB_PASSWORD: glpi

volumes:
  db_data:
